feat: SLW-1190
makeomatic/ms-users pull request #527
Opened 2021-09-29 07:58 UTC by WatchDG

2021-09-29 08:16 UTC, BrRenat requested changes

2021-09-29 08:16 UTC, BrRenat commented on src/utils/bypass/masters.js
> +    return userProfile.userId;
userProfile.email

2021-09-29 08:40 UTC, WatchDG commented on src/utils/bypass/masters.js
> +    return userProfile.userId;
changed to userProfile.email

2021-10-06 03:34 UTC, merged

2021-10-06 03:48 UTC, AVVS commented
:tada: This PR is included in version 14.23.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ms-users/v/14.23.0)
- [GitHub release](https://github.com/makeomatic/ms-users/releases/tag/v14.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: