feat: refresh tokens
makeomatic/ms-users pull request #530
Opened 2021-11-03 08:21 UTC by pajgo

2022-01-26 14:33 UTC, kulikovcappasity requested changes

2022-01-26 14:33 UTC, kulikovcappasity commented on src/utils/jwt-legacy.js
> +    throw new Errors.HttpStatusError(403, 'token has expired or was forged');
401, 'unauthorized'
Мы используем протухший токен, а значит мы не авотризованы. 403 надо кидать, когда юзер авторизован, но не имеет доступа к инфе, получаемой по эндпоинту

См:
https://www.rfc-editor.org/rfc/rfc2616#section-10.4.2
https://www.rfc-editor.org/rfc/rfc7231#section-6.5.3
https://www.rfc-editor.org/rfc/rfc7235#section-3.1

2022-01-26 15:52 UTC, pajgo commented on rfcs/stateless-auth.md
> +The token with short TTL, generally passed with all requests, except `users.refresh` and `users.logout`.
После последних правок, access token в хедере должен передаваться  для всех запросов кроме: login, refresh, logout.  До этого был момент, что logout требовал access token, но это исправлено, возможно  я пропустил обновление `apidoc`.

TTL проверяется в любом случае.

2022-01-26 15:52 UTC, pajgo commented on rfcs/stateless-auth.md
> +* Expires on `users.logout`.
👍 - Согласен, решаемо парой строк кода :) **Б** - безопасность.

Изначально процесс происходил именно так, но черт дернул упростить.

2022-01-26 15:52 UTC, pajgo commented on rfcs/stateless-auth.md
> +* Expires on `exp` date.
Сама идея stateless токенов как раз в том, что мы не храним информацию о токенах на сервере, а храним только набор правил для проверки валидности токена.

Поэтому присутсвует специальное для этого поле которое используется в процессе проверки.
Если мы хотим получить токены которые будут бесконечными и захотим предоставить пользователю обновить пару ключей через год/2года(далекое обозримое будущее), то можем избавиться от этого поля, но тогда будет определенная уязвимость в процессе.

2022-01-26 15:52 UTC, pajgo commented on rfcs/stateless-auth.md
> +* Expires when `RefreshToken` revoked.
В текущей реализации AccessToken.exp никогда не мог быть больше чем exp Refresh токена(он не перевыпускался).

При перевыпуске пары токенов при `refresh` это и будет так :) точнее AccessToken.exp будет приходиться в период < RefreshToken.exp всегда.

2022-01-26 15:55 UTC, pajgo commented on src/utils/jwt-legacy.js
> +    throw new Errors.HttpStatusError(403, 'token has expired or was forged');
Вот тут проблема, `legacy` мы оставляем как есть, т/к/ я не могу точно сказать, что это изменение не приведёт к поломке и сервис должен быть совместим с прошлыми версиями. Это касается и https://github.com/makeomatic/ms-users/pull/530#discussion_r792664250
😄

2022-01-27 06:41 UTC, kulikovcappasity commented on rfcs/stateless-auth.md
> +The token with short TTL, generally passed with all requests, except `users.refresh` and `users.logout`.
Можешь заслать полный список запросов? У нас же еще есть двухфакторка, восстановление доступа и регистрация

2022-01-27 06:42 UTC, kulikovcappasity commented on rfcs/stateless-auth.md
> +* Expires on `exp` date.
Не понял. А если у юзера угнали аккаунт, и он хочет поменять пароль, чтобы отрубить доступ злоумышленникам?

2022-01-27 06:43 UTC, kulikovcappasity commented on src/utils/jwt-legacy.js
> +    throw new Errors.HttpStatusError(403, 'token has expired or was forged');
Тогда хоть в техдолг поставь таску, а то вертеть стандарты - не очень хорошо)

2022-01-27 06:44 UTC, kulikovcappasity commented on src/utils/jwt-legacy.js
> +    throw new Errors.HttpStatusError(403, 'token has expired or was forged');
А вот по поводу 530 - это критический момент

2022-01-27 08:19 UTC, kulikovcappasity commented on rfcs/stateless-auth.md
> +* Expires when `RefreshToken` revoked.
Так он и не будет больше. Тут же речь про аксес токен

2022-01-27 08:20 UTC, kulikovcappasity commented on rfcs/stateless-auth.md
> +* Expires when `RefreshToken` revoked.
Так он и не будет больше. Тут же речь про аксес токен

2022-01-28 15:47 UTC, dshumova commented on src/utils/jwt-legacy.js
> +    throw new Errors.HttpStatusError(403, 'token has expired or was forged');
а используется ли этот метод где-то, кроме наших клиентов? если нет, то это легаси можно смело переписать, так как в десктопе и iOS logout() не вызывается никогда, а андроид сейчас в стадии беты

2022-02-02 05:10 UTC, WatchDG commented on rfcs/stateless-auth.md
> +* Expires on `users.logout`.
сам по себе он не тухнет, а перевыпускается; 
перевыпуск удаляет или перезаписывает старое значение для каждого из устройств;
у клиента может быть сколько угодно refresh token (не протухших), но должно обеспечиваться условие, что существует только одно действующие значение для каждого из устройств у проверяющего приложения, по нему же и должен происходить обмен значениями, по остальным возвращается ошибка авторизации

2022-02-02 05:19 UTC, WatchDG commented on rfcs/stateless-auth.md
> +* Always expires on `RefreshToken.exp`.
состояние AccessToken не должно зависеть от состояния RefreshToken; при этом согласовать значения протухания между ними можно: AccessToken.exp = RefreshToken.exp , но смысла в этом не так много; 
это практический момент который заключается в том, что RefreshToken следует действовать столько же сколько и AccessToken или больше, но и нарушении этого условия не должно быть проблемой

2022-02-02 05:29 UTC, WatchDG commented on rfcs/stateless-auth.md
> +* Expires when `RefreshToken` revoked.
опять же состояние AccessToken не должно зависеть от состояния RefreshToken;
отзыв или перевыпуск RefreshToken никак не влияет на AccessToken; чтобы все таки это организовать нужно вводить black list на подписи AccessToken и при отзыве/перевыпуске RefreshToken добавлять туда значение существующего AccessToken от предыдущего значения RefreshToken;
проверяющее приложение при этот должно сначала проверить сам AccessToken, а уже потом проверить отсутствие егов black list

2022-02-02 05:38 UTC, WatchDG commented on rfcs/stateless-auth.md
> +  // app specific payload
дублировать данные от AccessToken смысла нет;
могут быть данные которые влияют на процесс обмена на новый токен

2022-02-02 05:40 UTC, WatchDG commented on rfcs/stateless-auth.md
> +type RefreshToken = {
RefreshToken не обязательно должен быть JWT;
и данные о его типе irt и времени действия exp могут отсутствовать;

2022-04-05 11:54 UTC, merged