feat: add-provider-to-bypass-config
makeomatic/ms-users pull request #540
Opened 2022-02-08 19:02 UTC by WatchDG

2022-02-08 21:25 UTC, AVVS commented on src/users.js
> +    for (const [schemeName] of bypassesMasters) {
https://github.com/makeomatic/ms-users/blob/master/src/utils/bypass/masters.js

сам файл будет всегда брать config.masters - нужно сам провайдер тогда инстанциировать с нужным когфигом а не читать его из this

2022-02-09 07:38 UTC, BrRenat requested changes

2022-02-09 07:38 UTC, BrRenat commented on src/users.js
> +    for (const [schemeName, schemeConfig] of bypassesMasters) {
зачем трижды по массиву проходить?
initMastersService = () => {
 if (masters && enabled) {
        const MastersService = require('./utils/bypass/masters');
        this.bypass.masters = new MastersService(this);
        this.bypass[schemeName] = new MastersService(this, schemeConfig);
 }
}
addConnector(() => {
 Object.entries(this.config.bypass).map(initMastersService)
})

2022-02-09 09:31 UTC, WatchDG commented on src/users.js
> +    for (const [schemeName, schemeConfig] of bypassesMasters) {
в этом нет никаких проблем, это происходит единожды при инициализации сервиса и количество элементов крайне маленькое

а вот с map могут возникнуть, например когда нужно будет вывести в лог список инициализированных схем для masters;

и map создает новый массив и основная его задача трансформация данных, а не фильтрация, поэтому в таких случаях лучше использовать .filter(...).map(...)

2022-02-09 17:17 UTC, merged

2022-02-09 17:49 UTC, AVVS commented
:tada: This PR is included in version 14.25.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ms-users/v/14.25.0)
- [GitHub release](https://github.com/makeomatic/ms-users/releases/tag/v14.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: